"""
groundeval/core.py
=======================
Protocol definitions and shared data models.

The framework separates three concerns:
  1. CorpusAdapter  — how to fetch artifacts (MongoDB, files, or nothing)
  2. AccessPolicy   — who can see what subsystem at what time
  3. EventLog       — the ground-truth bus (JSONL or any iterable of LogEvent)


"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Any, Literal, Protocol, runtime_checkable


@dataclass
class LogEvent:
    """
    The minimal event record the framework needs.

    Users supply events as JSONL with at minimum:
        id, type, timestamp, actors, artifact_ids, facts

    Extra fields are preserved in `extras` and available to causal link
    matchers via event.extras.get("your_field").

    timestamp must be an ISO-8601 string: "2026-01-15T09:30:00"
    actors is a list of actor/user IDs who participated in this event.
    artifact_ids maps artifact type → artifact ID(s).
    facts is a free-form dict of event-specific payload.
    """

    id: str
    type: str
    timestamp: str
    actors: list[str] = field(default_factory=list)
    artifact_ids: dict[str, Any] = field(default_factory=dict)
    facts: dict[str, Any] = field(default_factory=dict)
    extras: dict[str, Any] = field(default_factory=dict)

    def ts(self) -> datetime:
        return datetime.fromisoformat(self.timestamp)

    @classmethod
    def from_dict(cls, d: dict) -> LogEvent:
        known = {"id", "type", "timestamp", "actors", "artifact_ids", "facts"}
        return cls(
            id=str(d.get("id", "")),
            type=str(d.get("type", "")),
            timestamp=str(d.get("timestamp", "")),
            actors=list(d.get("actors", [])),
            artifact_ids=dict(d.get("artifact_ids", {})),
            facts=dict(d.get("facts", {})),
            extras={k: v for k, v in d.items() if k not in known},
        )

    def to_dict(self) -> dict:
        return asdict(self)

    def resolve(self, dotted_path: str) -> Any:
        """Retrieve a value from a nested attribute path like 'facts.priority'."""
        return _get_nested(self.to_dict(), dotted_path)


@dataclass
class ToolCall:
    tool_name: str
    arguments: dict[str, Any]
    result_ids: list[str]
    timestamp_applied: str | None
    horizon_violation: bool
    actor_gate_violation: bool
    subsystem_violation: bool
    returned_empty: bool
    latency_ms: float


@dataclass
class AgentTrajectory:
    question_id: str
    question_type: str
    tool_calls: list[ToolCall] = field(default_factory=list)
    cited_artifacts: list[str] = field(default_factory=list)
    final_answer: dict[str, Any] = field(default_factory=dict)
    total_latency_ms: float = 0.0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    horizon_violations: int = 0
    actor_gate_violations: int = 0
    subsystem_violations: int = 0
    search_space_coverage: float = 0.0
    causal_mechanism_found: bool = False
    dead_ends_hit: int = 0
    dead_ends_recovered: int = 0
    budget_exceeded: bool = False


@dataclass
class CausalLink:
    """
    A verified cause → effect relationship extracted from the event log.
    Generated by CausalLinkIndexer; consumed by question generators and scorers.
    """

    link_type: str
    cause_event_id: str
    cause_event_type: str
    cause_timestamp: str
    effect_event_id: str
    effect_event_type: str
    effect_timestamp: str
    actors: list[str]
    counterfactual_premise: str
    counterfactual_outcome: str
    outcome_changed: bool
    evidence_artifact_ids: list[str] = field(default_factory=list)
    cause_artifact_ids: list[str] = field(default_factory=list)
    effect_artifact_ids: list[str] = field(default_factory=list)
    mechanism_aliases: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class AbsenceRecord:
    """
    A trigger event fired but its expected response event did not.
    Verified from the event log — not inferred.
    """

    trigger_event_id: str
    trigger_event_type: str
    trigger_timestamp: str
    trigger_actors: list[str]
    expected_response_type: str
    expected_search_space: list[str]
    subsystem: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class SearchSpaceSelector:
    """
    Declares how to build a portion of the expected search space for a
    silence question.  Either `id_template` or `query_template` must be set.

    Templates may reference trigger event fields via bracket notation:
        {artifact_ids.jira}
        {facts.account_id}
        {timestamp}
    """

    subsystem: str
    id_template: str | None = None
    query_template: str | None = None

    def render(self, trigger_event: LogEvent) -> dict[str, Any]:
        """
        Returns a runtime search request dict:
          {'mode': 'id', 'value': 'ENG-42'}   or
          {'mode': 'query', 'value': 'postmortem ENG-42'}
        """
        import re

        pattern = re.compile(r"\{([^}]+)\}")

        def replacer(m: Any) -> str:
            path = m.group(1)
            val = trigger_event.resolve(path)
            return str(val) if val is not None else ""

        if self.id_template:
            return {"mode": "id", "value": pattern.sub(replacer, self.id_template)}
        if self.query_template:
            return {
                "mode": "query",
                "value": pattern.sub(replacer, self.query_template),
            }
        raise ValueError("SearchSpaceSelector needs id_template or query_template")

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> SearchSpaceSelector:
        return cls(
            subsystem=d["subsystem"],
            id_template=d.get("id_template"),
            query_template=d.get("query_template"),
        )


@dataclass
class EvalQuestion:
    """
    Canonical question record written to eval_questions.json.
    All three tracks share this schema; unused fields are None.
    """

    question_id: str
    question_type: Literal["PERSPECTIVE", "COUNTERFACTUAL", "SILENCE"]
    question_text: str
    difficulty: Literal["easy", "medium", "hard"]
    ground_truth: dict[str, Any]

    actor: str | None = None
    actor_role: str | None = None
    as_of_time: str | None = None
    actor_visible_artifacts: list[str] | None = None
    actor_subsystem_access: list[str] | None = None
    cross_subsystem: bool = False

    causal_link: dict[str, Any] | None = None

    expected_search_space: list[str] | None = None

    expected_answer_schema: dict[str, Any] | None = None

    def to_dict(self) -> dict:
        d = asdict(self)
        # Visibility cones are recomputed at eval time; omit to keep JSON compact.
        d.pop("actor_visible_artifacts", None)
        d.pop("evidence_artifacts", None)
        return d


@dataclass
class EvalResult:
    question_id: str
    question_type: str
    difficulty: str
    answer_score: float
    answer_correct: bool
    trajectory_score: float
    combined_score: float
    failure_reason: str | None
    tool_call_count: int
    meta: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


@runtime_checkable
class CorpusAdapter(Protocol):
    """
    Provides artifact retrieval for the gated tool layer.

    Two built-in implementations are provided:
      - FileCorpusAdapter   — artifacts are files in a directory
      - NullCorpusAdapter   — context-injection mode, no retrieval needed

    Implement this protocol to plug in MongoDB, Elasticsearch, etc.
    """

    def fetch(self, artifact_id: str, as_of: str | None = None) -> dict | None:
        """Return artifact dict or None if not found / gated by timestamp."""
        ...

    def search(
        self,
        query: str,
        artifact_type: str | None = None,
        as_of: str | None = None,
        limit: int = 10,
    ) -> list[dict]:
        """Full-text or keyword search. Return list of artifact dicts."""
        ...

    def timestamp_of(self, artifact_id: str) -> str | None:
        """Return ISO timestamp of artifact creation, or None."""
        ...

    def subsystem_of(self, artifact_id: str) -> str | None:
        """Return subsystem name for this artifact (e.g. 'email', 'jira')."""
        ...

    def list_ids(self, subsystem: str | None = None) -> list[str]:
        """List all artifact IDs, optionally filtered by subsystem."""
        ...


@runtime_checkable
class AccessPolicy(Protocol):
    """
    Declares who can see what.

    The simplest implementation reads from config.yaml:

        roles:
          engineer:
            subsystems: [jira, git, slack, confluence]
          sales:
            subsystems: [salesforce, email, slack]

    Implement this protocol for more dynamic rules (e.g. per-project access).
    """

    def subsystems_for_role(self, role: str) -> set[str]:
        """Return set of subsystem names accessible to this role."""
        ...

    def role_for_actor(self, actor_id: str) -> str | None:
        """Return the role name for this actor, or None if unknown."""
        ...

    def visible_artifacts(
        self,
        actor_id: str,
        all_artifact_ids: list[str],
        as_of: str | None = None,
        corpus: CorpusAdapter | None = None,
    ) -> set[str]:
        """
        Return the subset of artifact IDs visible to this actor.

        Default implementation: all artifacts whose subsystem is in the
        actor's role subsystem set. Override for finer-grained control
        (e.g. direct-involvement tracking from an event log).
        """
        ...


@dataclass
class CausalJoinSpec:
    """
    A single join condition for linking a cause event to an effect event.

    Fields are dotted paths into the event dictionaries:
        cause:  "artifact_ids.jira"
        effect: "facts.source_ticket"

    A CausalLinkSpec may contain a list of these; ALL must match for a
    candidate effect to be accepted.
    """

    cause: str
    effect: str

    @classmethod
    def from_dict(cls, d: dict) -> CausalJoinSpec:
        return cls(cause=d["cause"], effect=d["effect"])

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class CausalLinkSpec:
    """
    User-supplied definition of one causal relationship type.

    Minimal config:
        name: ticket_closed_after_escalation
        cause_event_type: escalation_opened
        effect_event_type: ticket_closed
        premise_template: "the escalation had been resolved proactively"
        outcome_template: "the ticket would have closed earlier"
        outcome_changed: true

    Optional match_field / match_value narrow which events qualify:
        match_field: facts.priority
        match_value: "high"

    Optional max_gap_days limits cause→effect window (default: no limit).

    Optional join conditions (list of CausalJoinSpec) enforce that a shared
    identifier or field value connects the cause and effect events, so you do
    not rely on simple temporal adjacency alone.
    """

    name: str
    cause_event_type: str
    effect_event_type: str
    premise_template: str
    outcome_template: str
    outcome_changed: bool = True
    match_field: str | None = None
    match_value: Any | None = None
    max_gap_days: float | None = None
    link_field: str = "id"
    join: list[CausalJoinSpec] = field(default_factory=list)
    mechanism_aliases: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: dict) -> CausalLinkSpec:
        join_raw = d.get("join", [])
        join = [
            CausalJoinSpec.from_dict(j) if isinstance(j, dict) else CausalJoinSpec(**j)
            for j in (join_raw if isinstance(join_raw, list) else [join_raw])
        ]
        return cls(
            name=d["name"],
            cause_event_type=d["cause_event_type"],
            effect_event_type=d["effect_event_type"],
            premise_template=d["premise_template"],
            outcome_template=d["outcome_template"],
            outcome_changed=bool(d.get("outcome_changed", True)),
            match_field=d.get("match_field"),
            match_value=d.get("match_value"),
            max_gap_days=d.get("max_gap_days"),
            link_field=d.get("link_field", "id"),
            mechanism_aliases=list(d.get("mechanism_aliases", [])),
            join=join,
        )


@dataclass
class SilencePairSpec:
    """
    User-supplied definition of an expected trigger→response pair.

    When a trigger_event_type fires but response_event_type never follows
    (within max_gap_days), that's a verified absence.

    search_space_subsystems tells the scorer which subsystems the agent
    must check before concluding absence.

    search_space_selectors lets the user declare precise templates (by
    subsystem) so the expected search space is intentional rather than a
    broad subsystem sample.
    """

    trigger_event_type: str
    response_event_type: str
    search_space_subsystems: list[str] = field(default_factory=list)
    search_space_selectors: list[SearchSpaceSelector] = field(default_factory=list)
    max_gap_days: float | None = None
    match_field: str | None = None
    match_value: Any | None = None
    join: list[CausalJoinSpec] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: dict) -> SilencePairSpec:
        selectors_raw = d.get("search_space_selectors", d.get("search_space", []))
        selectors = [
            SearchSpaceSelector.from_dict(s) if isinstance(s, dict) else s
            for s in (
                selectors_raw if isinstance(selectors_raw, list) else [selectors_raw]
            )
        ]
        join_raw = d.get("join", [])
        join = [
            CausalJoinSpec.from_dict(j) if isinstance(j, dict) else CausalJoinSpec(**j)
            for j in (join_raw if isinstance(join_raw, list) else [join_raw])
        ]
        return cls(
            trigger_event_type=d["trigger_event_type"],
            response_event_type=d["response_event_type"],
            search_space_subsystems=list(d.get("search_space_subsystems", [])),
            search_space_selectors=selectors,
            max_gap_days=d.get("max_gap_days"),
            match_field=d.get("match_field"),
            match_value=d.get("match_value"),
            join=join,
        )


@dataclass
class PerspectiveConfig:
    positive_ratio: float = 0.5
    negative_permission_ratio: float = 0.25
    negative_temporal_ratio: float = 0.25
    require_cross_subsystem_cases: bool = True
    easy_ratio: float = 0.34
    medium_ratio: float = 0.33
    hard_ratio: float = 0.33

    @classmethod
    def from_dict(cls, d: dict) -> PerspectiveConfig:
        return cls(
            positive_ratio=float(d.get("positive_ratio", 0.5)),
            negative_permission_ratio=float(d.get("negative_permission_ratio", 0.25)),
            negative_temporal_ratio=float(d.get("negative_temporal_ratio", 0.25)),
            require_cross_subsystem_cases=bool(
                d.get("require_cross_subsystem_cases", True)
            ),
            easy_ratio=float(d.get("easy_ratio", 0.34)),
            medium_ratio=float(d.get("medium_ratio", 0.33)),
            hard_ratio=float(d.get("hard_ratio", 0.33)),
        )


class GatedRuntime:
    """
    First-class trace-capture runtime.

    Wraps a CorpusAdapter + AccessPolicy and enforces gates per question type:
      - PERSPECTIVE: temporal gate (as_of_time) + actor gate (visibility cone)
      - COUNTERFACTUAL: temporal gate only
      - SILENCE: no temporal gate (agent sees full corpus)

    Exposed methods mirror ``CorpusAdapter`` but emit gated results, record
    every call in a ``ToolCall`` log, and build a live ``AgentTrajectory``.

    Usage::

        runtime = GatedRuntime(corpus=corpus, policy=policy, question=question)
        doc = runtime.fetch("email-001")          # returns None if gated out
        results = runtime.search("foo", limit=5)  # gated search
        traj = runtime.trajectory()               # current trace so far

    All violations are recorded internally; the scorer later consumes them.
    """

    def __init__(
        self,
        corpus: CorpusAdapter,
        policy: AccessPolicy,
        question: EvalQuestion,
        actor_visible_artifacts: set[str] | None = None,
        actor_subsystem_access: set[str] | None = None,
    ):
        self._corpus = corpus
        self._policy = policy
        self._question = question
        self._qtype = question.question_type
        self._as_of = question.as_of_time
        self._actor_visible = actor_visible_artifacts or set()
        self._actor_subsystems = actor_subsystem_access or set()
        self._call_log: list[ToolCall] = []
        self._trajectory = AgentTrajectory(
            question_id=question.question_id,
            question_type=question.question_type,
        )

        if self._qtype == "SILENCE":
            self._as_of = None

        self._all_subsystems: list[str] = []

    @property
    def call_log(self) -> list[ToolCall]:
        return list(self._call_log)

    @property
    def all_subsystems(self) -> list[str]:
        return list(self._all_subsystems)

    def trajectory(self) -> AgentTrajectory:
        """Return the live trajectory populated so far."""
        t = self._trajectory
        t.tool_calls = list(self._call_log)
        t.horizon_violations = sum(1 for c in self._call_log if c.horizon_violation)
        t.actor_gate_violations = sum(
            1 for c in self._call_log if c.actor_gate_violation
        )
        t.subsystem_violations = sum(1 for c in self._call_log if c.subsystem_violation)
        t.dead_ends_hit = sum(1 for c in self._call_log if c.returned_empty)
        recovered = 0
        for i in range(len(self._call_log) - 1):
            if (
                self._call_log[i].returned_empty
                and not self._call_log[i + 1].returned_empty
            ):
                recovered += 1
        t.dead_ends_recovered = recovered
        return t

    def fetch(self, artifact_id: str) -> dict | None:
        """Return artifact dict or None if gated."""
        import time

        t0 = time.time()

        doc = self._corpus.fetch(artifact_id)
        horizon = False
        if self._as_of and doc:
            ts = self._corpus.timestamp_of(artifact_id)
            if ts and ts > self._as_of:
                doc = None
                horizon = True

        actor_v, sub_v = False, False
        if doc and self._qtype == "PERSPECTIVE":
            sub = self._corpus.subsystem_of(artifact_id)
            if self._actor_subsystems and sub and sub not in self._actor_subsystems:
                sub_v = True
                doc = None
            if self._actor_visible and artifact_id not in self._actor_visible:
                actor_v = True
                doc = None

        filtered = self._record(
            tool_name="fetch_artifact",
            arguments={"artifact_id": artifact_id},
            results=[doc] if doc else [],
            t0=t0,
            horizon_violation=horizon,
            actor_gate_violation=actor_v,
            subsystem_violation=sub_v,
            timestamp_applied=self._as_of,
        )
        return filtered[0] if filtered else None

    # Fields that are always safe to include in search results.
    # Everything else is excluded — the agent must call fetch_artifact()
    # to get full content. This keeps prompt tokens manageable across
    # multi-turn searches regardless of corpus size.
    _SEARCH_INCLUDE_FIELDS = frozenset({
        "id",
        "_id",
        "type",
        "title",
        "timestamp",
        "date",
        "created_at",
        "actors",
        "participants",
        "subsystem",
        "summary",
        "description",
    })

    def search(
        self,
        query: str,
        artifact_type: str | None = None,
        limit: int = 10,
    ) -> list[dict]:
        """Gated search — results are post-filtered by as_of and actor cone.

        Search results are stripped to metadata-only (id, type, title,
        timestamp, actors, summary).  When the agent wants full content,
        it must call fetch_artifact() — the same pattern OrgForge uses
        to keep prompt tokens from exploding across multi-turn searches.
        """
        import time

        t0 = time.time()

        raw = self._corpus.search(
            query, artifact_type=artifact_type, as_of=self._as_of, limit=limit
        )

        for doc in raw:
            keys = list(doc.keys())
            for key in keys:
                if key not in self._SEARCH_INCLUDE_FIELDS:
                    doc.pop(key, None)

        sub_v = False
        if self._qtype == "PERSPECTIVE" and artifact_type:
            if self._actor_subsystems and artifact_type not in self._actor_subsystems:
                sub_v = True
                return self._record(
                    tool_name="search_artifacts",
                    arguments={
                        "query": query,
                        "artifact_type": artifact_type,
                        "limit": limit,
                    },
                    results=[],
                    t0=t0,
                    horizon_violation=False,
                    actor_gate_violation=False,
                    subsystem_violation=sub_v,
                    timestamp_applied=self._as_of,
                )

        return self._record(
            tool_name="search_artifacts",
            arguments={"query": query, "artifact_type": artifact_type, "limit": limit},
            results=raw,
            t0=t0,
            horizon_violation=False,
            actor_gate_violation=False,
            subsystem_violation=sub_v,
            timestamp_applied=self._as_of,
        )

    def timestamp_of(self, artifact_id: str) -> str | None:
        return self._corpus.timestamp_of(artifact_id)

    def subsystem_of(self, artifact_id: str) -> str | None:
        return self._corpus.subsystem_of(artifact_id)

    def list_ids(self, subsystem: str | None = None) -> list[str]:
        if self._qtype == "PERSPECTIVE" and subsystem:
            if self._actor_subsystems and subsystem not in self._actor_subsystems:
                return []
        if self._qtype == "PERSPECTIVE" and self._actor_visible:
            all_ids = self._corpus.list_ids(subsystem=subsystem)
            return [aid for aid in all_ids if aid in self._actor_visible]
        return self._corpus.list_ids(subsystem=subsystem)

    def _record(
        self,
        tool_name: str,
        arguments: dict[str, Any],
        results: list[dict],
        t0: float,
        horizon_violation: bool = False,
        actor_gate_violation: bool = False,
        subsystem_violation: bool = False,
        timestamp_applied: str | None = None,
    ) -> list[dict]:
        import time

        latency = (time.time() - t0) * 1000

        filtered: list[dict] = []
        for r in results:
            doc_id = str(r.get("id", r.get("_id", "")))
            ts = r.get("timestamp") or r.get("created_at") or r.get("date", "")
            if self._as_of and ts and ts > self._as_of:
                horizon_violation = True
                continue
            filtered.append(r)

        for r in filtered:
            doc_id = str(r.get("id", r.get("_id", "")))
            subsystem = r.get("subsystem", "")
            if self._qtype == "PERSPECTIVE":
                if self._actor_visible and doc_id and doc_id not in self._actor_visible:
                    actor_gate_violation = True
                if (
                    self._actor_subsystems
                    and subsystem
                    and subsystem not in self._actor_subsystems
                ):
                    subsystem_violation = True

        tool_subsystem = arguments.get("artifact_type")
        if (
            self._qtype == "PERSPECTIVE"
            and tool_subsystem
            and self._actor_subsystems
            and tool_subsystem not in self._actor_subsystems
        ):
            subsystem_violation = True

        result_ids = [str(r.get("id", r.get("_id", ""))) for r in filtered]
        self._call_log.append(
            ToolCall(
                tool_name=tool_name,
                arguments=arguments,
                result_ids=result_ids,
                timestamp_applied=timestamp_applied,
                horizon_violation=horizon_violation,
                actor_gate_violation=actor_gate_violation,
                subsystem_violation=subsystem_violation,
                returned_empty=len(filtered) == 0,
                latency_ms=latency,
            )
        )
        return filtered


def _get_nested(d: dict, dotted_path: str) -> Any:
    """Retrieve a value from a nested dict or list using a dotted path string.
    Supports integer list indices, e.g. 'actors.0'."""
    parts = dotted_path.split(".")
    cur = d
    for p in parts:
        if isinstance(cur, dict):
            cur = cur.get(p)
        elif isinstance(cur, list):
            try:
                idx = int(p)
                cur = cur[idx] if 0 <= idx < len(cur) else None
            except ValueError:
                return None
        else:
            return None
    return cur


def load_events(path: Path) -> list[LogEvent]:
    """Load a JSONL event log. Each line must be a JSON object."""
    events = []
    with open(path) as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                events.append(LogEvent.from_dict(json.loads(line)))
            except Exception as exc:
                raise ValueError(f"Bad event on line {i + 1} of {path}: {exc}") from exc
    return events


ANSWER_SCHEMA_PERSPECTIVE: dict[str, Any] = {
    "type": "object",
    "required": [
        "could_actor_have_known",
        "reasoning",
        "evidence_artifacts",
        "blocked_subsystems",
    ],
    "properties": {
        "could_actor_have_known": {"type": "boolean"},
        "reasoning": {"type": "string"},
        "evidence_artifacts": {"type": "array", "items": {"type": "string"}},
        "blocked_subsystems": {"type": "array", "items": {"type": "string"}},
    },
}

ANSWER_SCHEMA_COUNTERFACTUAL: dict[str, Any] = {
    "type": "object",
    "required": [
        "outcome_changed",
        "causal_mechanism",
        "cause_event_id",
        "effect_event_id",
        "mechanism_direction",
        "evidence_artifacts",
        "actors",
        "reasoning",
    ],
    "properties": {
        "outcome_changed": {"type": "boolean"},
        "causal_mechanism": {
            "type": "string",
            "description": "The causal mechanism label selected from the question's causal contract.",
        },
        "cause_event_id": {
            "type": "string",
            "description": "The event ID of the cause event.",
        },
        "effect_event_id": {
            "type": "string",
            "description": "The event ID of the effect event.",
        },
        "mechanism_direction": {
            "type": "string",
            "enum": ["cause_to_effect", "effect_to_cause", "no_causal_link"],
            "description": "The direction of the causal relationship.",
        },
        "evidence_artifacts": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Artifact IDs used as evidence for the causal claim.",
        },
        "actors": {
            "type": "array",
            "items": {"type": "string"},
        },
        "reasoning": {"type": "string"},
    },
}

ANSWER_SCHEMA_SILENCE: dict[str, Any] = {
    "type": "object",
    "required": ["exists", "answer", "reasoning"],
    "properties": {
        "exists": {"type": "boolean"},
        "answer": {"type": "string", "enum": ["yes", "no"]},
        "reasoning": {"type": "string"},
    },
}

ANSWER_SCHEMAS: dict[str, dict[str, Any]] = {
    "PERSPECTIVE": ANSWER_SCHEMA_PERSPECTIVE,
    "COUNTERFACTUAL": ANSWER_SCHEMA_COUNTERFACTUAL,
    "SILENCE": ANSWER_SCHEMA_SILENCE,
}
